### PR TITLE
new cpp

### PR DESCRIPTION
**Pull request by shubhamsingla807**

### CODE REVIEW

**Comment by krishnakakade1999** [comment]
add your name in authors list then ill merge your pull request brother thank you

**Comment by shubhamsingla807** [comment]
> add your name in authors list then ill merge your pull request brother thank you

From where do I found author list

**Comment by krishnakakade1999** [comment]
> 
> 
> > add your name in authors list then ill merge your pull request brother thank you
> 
> From where do I found author list

>edit readme.md file and their your name last i hope you seen that before merging the pull request 🤔

**Comment by shubhamsingla807** [comment]
Done.

Sent from Mail for Windows 10

**Pull request merged**
